#!/usr/bin/env python3
"""Epistemic analysis for pharmacovigilance domain.

Generated by the epistract domain wizard.
Performs contradiction detection, confidence calibration,
gap analysis, and cross-document linking.
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path


# ---------------------------------------------------------------------------
# Domain-specific parameters
# ---------------------------------------------------------------------------

_CONTRADICTION_PAIRS = [['positive dechallenge', 'negative dechallenge'], ['positive rechallenge', 'negative rechallenge'], ['resolved', 'not recovered'], ['fatal', 'recovered'], ['causal', 'non-causal'], ['associated', 'unrelated'], ['faers', 'eudravigilance'], ['asserted causation', 'ruled out'], ['confirmed', 'refuted'], ['reproducible', 'isolated'], ['dose-dependent', 'dose-independent']]
_GAP_TARGET_TYPES = {'core_pharmacovigilance_coverage': ['Drug', 'AdverseEvent', 'Patient', 'Reporter', 'ReportType', 'Outcome'], 'causality_signal_coverage': ['DechallengeRechallenge', 'TemporalRelationship', 'CausalitySignal'], 'regulatory_signal_coverage': ['RegulatoryAction'], 'confounder_coverage': ['Concomitant', 'Indication']}
_CONFIDENCE_HIGH = 0.9
_CONFIDENCE_MEDIUM = 0.7
_CONFIDENCE_LOW = 0.5
_ENTITY_TYPES = ['Drug', 'AdverseEvent', 'Patient', 'Reporter', 'Outcome', 'ReportType', 'TemporalRelationship', 'Concomitant', 'Indication', 'DechallengeRechallenge', 'RegulatoryAction', 'CausalitySignal']


def analyze_pharmacovigilance_epistemic(
    output_dir: Path,
    graph_data: dict,
) -> dict:
    """Analyze epistemic status of pharmacovigilance knowledge graph.

    Args:
        output_dir: Directory containing graph outputs.
        graph_data: Parsed graph_data.json with nodes and links.

    Returns:
        Dict with keys: metadata, summary, base_domain, super_domain.
    """
    nodes = graph_data.get("nodes", [])
    links = graph_data.get("links", [])

    # --- Contradiction detection ---
    conflicts: list[dict] = []
    for pair in _CONTRADICTION_PAIRS:
        if len(pair) != 2:
            continue
        term_a, term_b = pair[0].lower(), pair[1].lower()
        for link in links:
            evidence = str(link.get("evidence", "")).lower()
            if term_a in evidence and term_b in evidence:
                conflicts.append({
                    "type": "contradiction",
                    "terms": [pair[0], pair[1]],
                    "relation": link.get("id", ""),
                    "evidence": link.get("evidence", ""),
                })

    # --- Confidence calibration ---
    asserted_count = 0
    hypothesized_count = 0
    unverified_count = 0

    for link in links:
        confidence = link.get("confidence", 0.5)
        if confidence >= _CONFIDENCE_HIGH:
            link["epistemic_status"] = "asserted"
            asserted_count += 1
        elif confidence >= _CONFIDENCE_MEDIUM:
            link["epistemic_status"] = "hypothesized"
            hypothesized_count += 1
        else:
            link["epistemic_status"] = "unverified"
            unverified_count += 1

    # --- Gap analysis ---
    gaps: list[dict] = []
    node_types = defaultdict(int)
    for node in nodes:
        node_types[node.get("entity_type", "")] += 1

    for gap_category, expected_types in _GAP_TARGET_TYPES.items():
        for expected in expected_types:
            if node_types.get(expected, 0) == 0:
                gaps.append({
                    "category": gap_category,
                    "missing_type": expected,
                    "description": f"No {expected} entities found in graph",
                })

    # --- Cross-document linking ---
    doc_entities: dict[str, set] = defaultdict(set)
    for node in nodes:
        for doc in node.get("source_documents", []):
            doc_entities[node.get("name", "")].add(doc)
    cross_doc_entities = [
        {"name": name, "document_count": len(docs)}
        for name, docs in doc_entities.items()
        if len(docs) > 1
    ]

    # --- Build claims_layer ---
    claims_layer = {
        "metadata": {
            "domain": "pharmacovigilance",
            "description": "Epistemic analysis for pharmacovigilance domain",
            "generated_from": str(output_dir / "graph_data.json"),
            "total_relations": len(links),
        },
        "summary": {
            "conflicts_found": len(conflicts),
            "gaps_found": len(gaps),
            "cross_document_entities": len(cross_doc_entities),
            "epistemic_status_counts": {
                "asserted": asserted_count,
                "hypothesized": hypothesized_count,
                "unverified": unverified_count,
            },
        },
        "base_domain": {
            "description": "Factual pharmacovigilance knowledge graph relations",
            "relation_count": asserted_count,
        },
        "super_domain": {
            "domain": "pharmacovigilance",
            "description": "Epistemic layer -- conflicts, gaps, cross-document linking",
            "conflicts": conflicts,
            "coverage_gaps": gaps,
            "cross_document_entities": cross_doc_entities,
        },
    }

    return claims_layer


# ------------------------------------------------------------------
# CUSTOM_RULES -- domain-specific epistemic rules (FIDL-07 opt-in)
# ------------------------------------------------------------------
# Each rule is a callable with signature:
#     rule(nodes: list[dict], links: list[dict], context: dict) -> list[dict]
# where context = {"output_dir", "graph_data", "domain_name"}.
# Rule failures are isolated (one exception logs status='error' but
# does NOT abort the phase). Findings merge into
# claims_layer["super_domain"]["custom_findings"][rule.__name__].
# See docs/known-limitations.md (Per-Domain Extensibility, FIDL-07)
# for the full contract. Example:
#
#     def my_rule(nodes, links, context):
#         return [{"rule_name": "my_rule", "type": "example",
#                   "severity": "INFO", "description": "x",
#                   "evidence": {}}]
#     CUSTOM_RULES.append(my_rule)

CUSTOM_RULES: list = []
