#!/usr/bin/env python3
"""Epistemic analysis for fda_product_labels domain.

Generated by the epistract domain wizard.
Performs contradiction detection, confidence calibration,
gap analysis, and cross-document linking.
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path


# ---------------------------------------------------------------------------
# Domain-specific parameters
# ---------------------------------------------------------------------------

_CONTRADICTION_PAIRS = [('INDICATION', 'CONTRAINDICATION'), ('ADVERSE_REACTION', 'INDICATION'), ('WARNING', 'INDICATION'), ('DRUG_INTERACTION', 'INDICATED_FOR')]
_GAP_TARGET_TYPES = {'MECHANISM_OF_ACTION': 'Many OTC and generic labels omit mechanism of action; flag absence as a knowledge gap.', 'PHARMACOKINETIC_PROPERTY': 'Labels lacking pharmacokinetics data cannot support dosing-adjustment decisions; flag when absent for Rx drugs.', 'CLINICAL_STUDY': 'Labels without referenced clinical studies provide weaker evidentiary grounding for efficacy claims.', 'PATIENT_POPULATION': 'Labels that do not address pediatric or geriatric populations leave formulary analysts without complete safety profiles.'}
_CONFIDENCE_HIGH = 0.9
_CONFIDENCE_MEDIUM = 0.7
_CONFIDENCE_LOW = 0.5
_ENTITY_TYPES = ['DRUG_PRODUCT', 'ACTIVE_INGREDIENT', 'INACTIVE_INGREDIENT', 'MANUFACTURER', 'INDICATION', 'CONTRAINDICATION', 'ADVERSE_REACTION', 'WARNING', 'DRUG_INTERACTION', 'DOSAGE_REGIMEN', 'PATIENT_POPULATION', 'MECHANISM_OF_ACTION', 'PHARMACOKINETIC_PROPERTY', 'CLINICAL_STUDY', 'PHARMACOLOGIC_CLASS', 'REGULATORY_IDENTIFIER']

# FDA SPL section / language markers used by the four-level epistemic classifier.
# Lowercased substrings; matched case-insensitively against link.evidence.
_ESTABLISHED_MARKERS = (
    "boxed warning",
    "contraindication",
    "contraindicated",
    "must not",
    "do not use",
    "warnings and precautions",
)
_OBSERVED_MARKERS = (
    "clinical studies",
    "clinical trial",
    "controlled trial",
    "randomized",
    "placebo-controlled",
    "placebo controlled",
    "double-blind",
    "double blind",
)
_REPORTED_MARKERS = (
    "adverse reactions",
    "postmarketing",
    "post-marketing",
    "post marketing",
    "spontaneous report",
    "post-marketing experience",
    "postmarket surveillance",
)
_THEORETICAL_MARKERS = (
    "clinical pharmacology",
    "mechanism of action",
    "pharmacodynamics",
    "in vitro",
    "in-vitro",
    "expected to",
    "is thought to",
)


def analyze_fda_product_labels_epistemic(
    output_dir: Path,
    graph_data: dict,
) -> dict:
    """Analyze epistemic status of fda_product_labels knowledge graph.

    Args:
        output_dir: Directory containing graph outputs.
        graph_data: Parsed graph_data.json with nodes and links.

    Returns:
        Dict with keys: metadata, summary, base_domain, super_domain.
    """
    nodes = graph_data.get("nodes", [])
    links = graph_data.get("links", [])

    # --- Contradiction detection ---
    conflicts: list[dict] = []
    for pair in _CONTRADICTION_PAIRS:
        if len(pair) != 2:
            continue
        term_a, term_b = pair[0].lower(), pair[1].lower()
        for link in links:
            evidence = str(link.get("evidence", "")).lower()
            if term_a in evidence and term_b in evidence:
                conflicts.append({
                    "type": "contradiction",
                    "terms": [pair[0], pair[1]],
                    "relation": link.get("id", ""),
                    "evidence": link.get("evidence", ""),
                })

    # --- FDA-specific epistemology classification (FDA-04) ---
    # Levels reflect the SPL labeling section semantics, not a raw confidence threshold:
    #   established  -- definitive labeling language (BOXED WARNING, CONTRAINDICATION,
    #                    "contraindicated", "must not", "do not use")
    #   observed     -- controlled clinical study data (CLINICAL STUDIES section,
    #                    "controlled trial", "randomized", "placebo")
    #   reported     -- postmarket / spontaneous data (ADVERSE REACTIONS, POSTMARKETING,
    #                    "spontaneous report", "post-marketing experience")
    #   theoretical  -- mechanism-of-action inference (CLINICAL PHARMACOLOGY,
    #                    "mechanism", "pharmacology", "in vitro", "expected to")
    # Confidence is the tiebreaker when no marker matches.

    established_count = 0
    observed_count = 0
    reported_count = 0
    theoretical_count = 0

    for link in links:
        evidence = str(link.get("evidence", "")).lower()
        confidence = link.get("confidence", 0.5)

        if any(marker in evidence for marker in _ESTABLISHED_MARKERS):
            level = "established"
        elif any(marker in evidence for marker in _OBSERVED_MARKERS):
            level = "observed"
        elif any(marker in evidence for marker in _REPORTED_MARKERS):
            level = "reported"
        elif any(marker in evidence for marker in _THEORETICAL_MARKERS):
            level = "theoretical"
        elif confidence >= _CONFIDENCE_HIGH:
            level = "established"
        elif confidence >= _CONFIDENCE_MEDIUM:
            level = "observed"
        elif confidence >= _CONFIDENCE_LOW:
            level = "reported"
        else:
            level = "theoretical"

        link["epistemic_status"] = level
        if level == "established":
            established_count += 1
        elif level == "observed":
            observed_count += 1
        elif level == "reported":
            reported_count += 1
        else:
            theoretical_count += 1

    # --- Gap analysis ---
    gaps: list[dict] = []
    node_types = defaultdict(int)
    for node in nodes:
        node_types[node.get("entity_type", "")] += 1

    for gap_category, expected_types in _GAP_TARGET_TYPES.items():
        for expected in expected_types:
            if node_types.get(expected, 0) == 0:
                gaps.append({
                    "category": gap_category,
                    "missing_type": expected,
                    "description": f"No {expected} entities found in graph",
                })

    # --- Cross-document linking ---
    doc_entities: dict[str, set] = defaultdict(set)
    for node in nodes:
        for doc in node.get("source_documents", []):
            doc_entities[node.get("name", "")].add(doc)
    cross_doc_entities = [
        {"name": name, "document_count": len(docs)}
        for name, docs in doc_entities.items()
        if len(docs) > 1
    ]

    # --- Build claims_layer ---
    claims_layer = {
        "metadata": {
            "domain": "fda_product_labels",
            "description": "Epistemic analysis for fda_product_labels domain",
            "generated_from": str(output_dir / "graph_data.json"),
            "total_relations": len(links),
        },
        "summary": {
            "conflicts_found": len(conflicts),
            "gaps_found": len(gaps),
            "cross_document_entities": len(cross_doc_entities),
            "epistemic_status_counts": {
                "established": established_count,
                "observed": observed_count,
                "reported": reported_count,
                "theoretical": theoretical_count,
            },
        },
        "base_domain": {
            "description": "Factual fda_product_labels knowledge graph relations",
            "relation_count": established_count,
        },
        "super_domain": {
            "domain": "fda_product_labels",
            "description": "Epistemic layer -- conflicts, gaps, cross-document linking",
            "conflicts": conflicts,
            "coverage_gaps": gaps,
            "cross_document_entities": cross_doc_entities,
        },
    }

    return claims_layer


def annotate_relations(
    output_dir: Path,
    graph_data: dict,
) -> dict:
    """REQUIREMENTS.md FDA-04 spelling alias.

    The framework dispatch convention is `analyze_{slug}_epistemic()`
    (see core/label_epistemic.py:654-663). REQUIREMENTS.md FDA-04 spells
    the function `annotate_relations()`; this alias delegates to the
    canonical implementation so both spellings are valid entry points.

    Args:
        output_dir: Directory containing graph outputs.
        graph_data: Parsed graph_data.json with nodes and links.

    Returns:
        Dict with keys: metadata, summary, base_domain, super_domain.
    """
    return analyze_fda_product_labels_epistemic(output_dir, graph_data)


# ------------------------------------------------------------------
# CUSTOM_RULES -- domain-specific epistemic rules (FIDL-07 opt-in)
# ------------------------------------------------------------------
# Each rule is a callable with signature:
#     rule(nodes: list[dict], links: list[dict], context: dict) -> list[dict]
# where context = {"output_dir", "graph_data", "domain_name"}.
# Rule failures are isolated (one exception logs status='error' but
# does NOT abort the phase). Findings merge into
# claims_layer["super_domain"]["custom_findings"][rule.__name__].
# See docs/known-limitations.md (Per-Domain Extensibility, FIDL-07)
# for the full contract. Example:
#
#     def my_rule(nodes, links, context):
#         return [{"rule_name": "my_rule", "type": "example",
#                   "severity": "INFO", "description": "x",
#                   "evidence": {}}]
#     CUSTOM_RULES.append(my_rule)

CUSTOM_RULES: list = []
